package com.intuit.qbo.ecommerce.krc.api.dto;

import java.util.Date;

/**
 * @author generated by Vijayan Srinivasan
 * @since Thu Oct 09 19:08:56 IST 2014
 */

public class CustomerDO {
	private String shopDomain;
	private String webApiKey;
	private Boolean syncStatus;
	private String email;
	private String companyName;
	private String firstName;
	private String lastName;
	private String address1;
	private String address2;
	private String city;
	private String state;
	private String postCode;
	private String country;
	private String tinNo;
	private String mobile;
	private String qbUserName;
	private String qbPassword;
	private String qbCompanyId;
	private Integer id;
	private Date createdDt;
	private Date updatedDt;
	private Date lastOrderSyncDate;
	private Date lastProductSyncDate;
	private Date accessTokenExpirationDate;
	private String accessToken;
	private String accessTokenSecret;
	private String tokenValidationMessage;
	private Long syncFrequency;
	private Long syncStatrDelay;
	
	

	public Long getSyncFrequency() {
		return syncFrequency;
	}

	public void setSyncFrequency(Long syncFrequency) {
		this.syncFrequency = syncFrequency;
	}

	public Long getSyncStatrDelay() {
		return syncStatrDelay;
	}

	public void setSyncStatrDelay(Long syncStatrDelay) {
		this.syncStatrDelay = syncStatrDelay;
	}

	public String getShopDomain() {
		return shopDomain;
	}

	public void setShopDomain(String shopDomain) {
		this.shopDomain = shopDomain;
	}

	public String getWebApiKey() {
		return webApiKey;
	}

	public void setWebApiKey(String webApiKey) {
		this.webApiKey = webApiKey;
	}

	public Boolean getSyncStatus() {
		return syncStatus;
	}

	public void setSyncStatus(Boolean syncStatus) {
		this.syncStatus = syncStatus;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPostCode() {
		return postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getTinNo() {
		return tinNo;
	}

	public void setTinNo(String tinNo) {
		this.tinNo = tinNo;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getQbUserName() {
		return qbUserName;
	}

	public void setQbUserName(String qbUserName) {
		this.qbUserName = qbUserName;
	}

	public String getQbPassword() {
		return qbPassword;
	}

	public void setQbPassword(String qbPassword) {
		this.qbPassword = qbPassword;
	}

	public String getQbCompanyId() {
		return qbCompanyId;
	}

	public void setQbCompanyId(String qbCompanyId) {
		this.qbCompanyId = qbCompanyId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getCreatedDt() {
		return createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public Date getUpdatedDt() {
		return updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	
	public Date getLastProductSyncDate() {
		return lastProductSyncDate;
	}

	
	
	@Override
	public String toString() {
		return "CustomerDO [shopDomain=" + shopDomain + ", webApiKey="
				+ webApiKey + ", syncStatus=" + syncStatus + ", email=" + email
				+ ", companyName=" + companyName + ", firstName=" + firstName
				+ ", lastName=" + lastName + ", address1=" + address1
				+ ", address2=" + address2 + ", city=" + city + ", state="
				+ state + ", postCode=" + postCode + ", country=" + country
				+ ", tinNo=" + tinNo + ", mobile=" + mobile + ", qbUserName="
				+ qbUserName + ", qbPassword=" + qbPassword + ", qbCompanyId="
				+ qbCompanyId + ", id=" + id + ", createdDt=" + createdDt
				+ ", updatedDt=" + updatedDt + ", lastOrderSyncDate="
				+ lastOrderSyncDate + ", lastProductSyncDate="
				+ lastProductSyncDate + ", accessTokenExpirationDate="
				+ accessTokenExpirationDate + ", accessToken=" + accessToken
				+ ", accessTokenSecret=" + accessTokenSecret
				+ ", tokenValidationMessage=" + tokenValidationMessage + "]";
	}

	public void setLastProductSyncDate(Date lastProductSyncDate) {
		this.lastProductSyncDate = lastProductSyncDate;
	}

	public Date getLastOrderSyncDate() {
		return lastOrderSyncDate;
	}

	public void setLastOrderSyncDate(Date lastOrderSyncDate) {
		this.lastOrderSyncDate = lastOrderSyncDate;
	}

	

	public Date getAccessTokenExpirationDate() {
		return accessTokenExpirationDate;
	}

	public void setAccessTokenExpirationDate(Date accessTokenExpirationDate) {
		this.accessTokenExpirationDate = accessTokenExpirationDate;
	}

	public String getAccessToken() {
		return accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public String getAccessTokenSecret() {
		return accessTokenSecret;
	}

	public void setAccessTokenSecret(String accessTokenSecret) {
		this.accessTokenSecret = accessTokenSecret;
	}

	public String getTokenValidationMessage() {
		return tokenValidationMessage;
	}

	public void setTokenValidationMessage(String tokenValidationMessage) {
		this.tokenValidationMessage = tokenValidationMessage;
	}
	
	

}